### ISSUE TITLE
running issue

### ISSUE THREAD

**Issue by mavajsunco** [gitjzu/serverless-graphql-boilerplate#1]

**Comment by gitjzu** [comment]
@mavajsunco 
Hi! Sorry for the super late reply, I somehow didn't get an alert.. 
What was your problem? :)

**Comment by mavajsunco** [comment]
that is cool, I could not run it initially, But I found the issue. But currently working fine, I only not understand why I can not test it on lambda and only via API call I can test it. Do you have time and will you able to help in more advanced level? for example, I am wondering how I could make it filterable for more fields and etc.

**Comment by gitjzu** [comment]
@mavajsunco Currently I'm a bit too busy to focus more on this project. My plan is to add more features like filterable fields in the future, but I can't say the exact time. If you want to contribute to this boilerplate with new features, pull requests are always welcome! :)
